"""empty message

Revision ID: 7d620304e903
Revises: e1c6976058ea
Create Date: 2019-10-22 13:44:52.911347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d620304e903'
down_revision = 'e1c6976058ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
