"""empty message

Revision ID: 976dce9242d1
Revises: 7d620304e903
Create Date: 2020-03-02 11:17:56.264523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976dce9242d1'
down_revision = '7d620304e903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
