"""empty message

Revision ID: e1c6976058ea
Revises: d66445449926
Create Date: 2019-10-22 13:44:02.522465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c6976058ea'
down_revision = 'd66445449926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
